# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ginkgo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ginkgo
  pod 'AWSCore', '~> 2.8.0'
  pod 'AWSMobileClient', '~> 2.8.0'
  pod 'AWSUserPoolsSignIn', '~> 2.8.0'
  pod 'AWSAuthUI', '~> 2.8.0'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RAMAnimatedTabBarController'
  pod 'R.swift'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'AlamofireObjectMapper'

  target 'ginkgoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
